# Generated by Django 5.2.7 on 2025-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_subjectgroup_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectgroup",
            options={
                "ordering": ["name"],
                "verbose_name": "Subject Group",
                "verbose_name_plural": "Subject Groups",
            },
        ),
        migrations.RemoveField(
            model_name="subjectgroup",
            name="class_model",
        ),
        migrations.AlterField(
            model_name="subjectgroup",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="group name"
            ),
        ),
    ]
