# Generated by Django 5.2.7 on 2025-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_subjectgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salarygrade",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="salarygrade",
            name="grade_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Grade 1"),
                    (2, "Grade 2"),
                    (3, "Grade 3"),
                    (4, "Grade 4"),
                    (5, "Grade 5"),
                    (6, "Grade 6"),
                    (7, "Grade 7"),
                    (8, "Grade 8"),
                ],
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="salarygrade",
            name="school",
        ),
    ]
