# Generated by Django 5.2.7 on 2025-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_salarygrade_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="staff",
            name="staff_school__0f983d_idx",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="school",
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["status"], name="staff_status_c91b08_idx"),
        ),
    ]
