# Generated by Django 5.2.7 on 2025-10-20 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_staff_staff_school__0f983d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(
                        help_text="Grade code: A, B, C, D, E, F",
                        max_length=2,
                        unique=True,
                        verbose_name="grade letter",
                    ),
                ),
                (
                    "grade_name",
                    models.CharField(
                        help_text="Display name: A1, A+, B2, etc.",
                        max_length=20,
                        verbose_name="grade name",
                    ),
                ),
                (
                    "grade_description",
                    models.CharField(
                        help_text="Text description: Excellent, Very Good, Good, etc.",
                        max_length=100,
                        verbose_name="grade description",
                    ),
                ),
                (
                    "min_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum score for this grade (e.g., 75.00)",
                        max_digits=5,
                        verbose_name="minimum score",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum score for this grade (e.g., 100.00)",
                        max_digits=5,
                        verbose_name="maximum score",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order for display (lower numbers first)",
                        verbose_name="display order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["order", "-min_score"],
            },
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="ca_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Continuous Assessment score (max 40)",
                max_digits=5,
                null=True,
                verbose_name="CA score",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="exam_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Examination score (max 60)",
                max_digits=5,
                null=True,
                verbose_name="exam score",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Rank in class for this subject",
                null=True,
                verbose_name="position",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="result_entered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="result entered at"
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="result_entered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results_entered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="result entered by",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="teacher_comment",
            field=models.TextField(
                blank=True,
                help_text="Subject teacher's remark",
                verbose_name="teacher comment",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="total_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Total = CA + Exam (max 100)",
                max_digits=5,
                null=True,
                verbose_name="total score",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                help_text="Auto-calculated based on total score",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_subjects",
                to="api.grade",
                verbose_name="grade",
            ),
        ),
    ]
