# Generated by Django 5.2.7 on 2025-10-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_grade_studentsubject_ca_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="ca_max",
            field=models.DecimalField(
                decimal_places=2,
                default=40,
                help_text="Maximum Continuous Assessment score (default: 40)",
                max_digits=5,
                verbose_name="CA maximum score",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="exam_max",
            field=models.DecimalField(
                decimal_places=2,
                default=60,
                help_text="Maximum Examination score (default: 60)",
                max_digits=5,
                verbose_name="Exam maximum score",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_letter",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                ],
                help_text="Grade letter: A, B, C, D, E, or F",
                max_length=1,
                unique=True,
                verbose_name="grade letter",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="order",
            field=models.PositiveSmallIntegerField(
                editable=False,
                help_text="Auto-generated from grade letter (A=1, B=2, etc.)",
                verbose_name="display order",
            ),
        ),
    ]
