# Generated by Django 5.2.7 on 2025-10-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_subject_ca_max_subject_exam_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="is_core",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="is_trade",
        ),
    ]
