# Generated by Django 5.2.7 on 2025-10-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated on acceptance (Format: YYYYMMDD + Serial)",
                max_length=10,
                unique=True,
                verbose_name="admission number",
            ),
        ),
    ]
