# Generated by Django 5.2.7 on 2025-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_exam_studentanswer_studentexam_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated on acceptance (Format: YYYYMMDD + Serial)",
                max_length=20,
                unique=True,
                verbose_name="admission number",
            ),
        ),
    ]
