# Generated by Django 5.2.7 on 2025-10-23 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Student club or society membership",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="api.club",
                verbose_name="club",
            ),
        ),
    ]
