# Generated by Django 5.2.7 on 2025-10-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_biodata_club_student_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="readable_id",
            field=models.CharField(
                blank=True,
                help_text="Human-readable ID like EXM-IEE83U7",
                max_length=20,
                unique=True,
                verbose_name="readable ID",
            ),
        ),
    ]
