# Generated by Django 5.2.7 on 2025-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_readable_id_to_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="readable_id",
            field=models.CharField(
                blank=True,
                help_text="Human-readable ID like STU-001ABC",
                max_length=20,
                unique=True,
                verbose_name="readable ID",
            ),
        ),
    ]
