# Generated by Django 5.2.7 on 2025-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_add_readable_id_to_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="readable_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="readable_id",
        ),
        migrations.AlterField(
            model_name="exam",
            name="id",
            field=models.CharField(
                help_text="Human-readable ID like EXM-IEE83U7",
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="exam ID",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.CharField(
                help_text="Human-readable ID like STU-001ABC",
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="student ID",
            ),
        ),
    ]
