# Generated by Django 5.2.7 on 2025-10-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_override_id_with_readable_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.RemoveIndex(
            model_name="exam",
            name="api_exam_status_eff29f_idx",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["status", "created_at"], name="api_exam_status_90aac7_idx"
            ),
        ),
    ]
