# Generated by Django 5.2.7 on 2025-11-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_exam_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Human-readable ID like ASM-IEE83U7",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="assignment ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="assignment title"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="instructions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select questions from the question bank",
                        related_name="assignments",
                        to="api.question",
                        verbose_name="questions",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="api.subject",
                        verbose_name="subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject"], name="api_assignm_subject_69aa08_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="api_assignm_status_762ce4_idx",
                    ),
                ],
            },
        ),
    ]
