# Generated by Django 5.2.7 on 2025-11-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="assigned_teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_classes",
                to="api.staff",
                verbose_name="assigned teachers",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="assigned_teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_subjects",
                to="api.staff",
                verbose_name="assigned teachers",
            ),
        ),
    ]
