# Generated by Django 5.2.7 on 2025-11-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_class_assigned_teachers_subject_assigned_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="School this staff member belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_members",
                to="api.school",
            ),
        ),
    ]
