# Generated by Django 5.2.7 on 2025-11-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_staff_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="school",
        ),
    ]
