# Generated by Django 5.2.7 on 2025-11-08 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_studentsubject_cleared_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsubject",
            name="cleared",
        ),
        migrations.RemoveField(
            model_name="studentsubject",
            name="cleared_at",
        ),
        migrations.RemoveField(
            model_name="studentsubject",
            name="cleared_by",
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="openday_clearance_checklist",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="open day clearance checklist"
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="openday_clearance_notes",
            field=models.TextField(blank=True, verbose_name="open day clearance notes"),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="openday_cleared",
            field=models.BooleanField(default=False, verbose_name="open day cleared"),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="openday_cleared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="open day cleared at"
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="openday_cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="open_day_cleared_subjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="open day cleared by",
            ),
        ),
    ]
