# Generated by Django 5.2.7 on 2025-11-08 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_studentsubject_cleared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubject",
            name="cleared",
            field=models.BooleanField(default=False, verbose_name="cleared"),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="cleared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="cleared at"
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_subjects_cleared",
                to=settings.AUTH_USER_MODEL,
                verbose_name="cleared by",
            ),
        ),
    ]
