# Generated by Django 5.2.7 on 2025-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_studentsubject_cleared_studentsubject_cleared_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarygrade",
            name="grade_number",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Grade 1"),
                    (2, "Grade 2"),
                    (3, "Grade 3"),
                    (4, "Grade 4"),
                    (5, "Grade 5"),
                    (6, "Grade 6"),
                    (7, "Grade 7"),
                    (8, "Grade 8"),
                    (9, "Grade 9"),
                    (10, "Grade 10"),
                    (11, "Grade 11"),
                    (12, "Grade 12"),
                    (13, "Grade 13"),
                    (14, "Grade 14"),
                    (15, "Grade 15"),
                    (16, "Grade 16"),
                    (17, "Grade 17"),
                    (18, "Grade 18"),
                ],
                unique=True,
            ),
        ),
    ]
