# Generated by Django 5.2.7 on 2025-11-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_staff_personal_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamHall",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="hall name"
                    ),
                ),
                (
                    "number_of_seats",
                    models.PositiveIntegerField(
                        help_text="Total seating capacity of the exam hall",
                        verbose_name="number of seats",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive halls won't be available for exam scheduling",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Exam Hall",
                "verbose_name_plural": "Exam Halls",
                "ordering": ["name"],
            },
        ),
    ]
