# Generated by Django 5.2.7 on 2025-11-19 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_examhall"),
    ]

    operations = [
        migrations.CreateModel(
            name="CBTExamCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit passcode",
                        max_length=6,
                        unique=True,
                        verbose_name="passcode",
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Seat number in the exam hall",
                        null=True,
                        verbose_name="seat number",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this code has been used",
                        verbose_name="used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this passcode expires",
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cbt_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exam this code is for (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbt_codes",
                        to="api.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "exam_hall",
                    models.ForeignKey(
                        blank=True,
                        help_text="Exam hall assigned to this student",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cbt_codes",
                        to="api.examhall",
                        verbose_name="exam hall",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student this code is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbt_exam_codes",
                        to="api.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "CBT Exam Code",
                "verbose_name_plural": "CBT Exam Codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="api_cbtexam_code_64fccf_idx"),
                    models.Index(
                        fields=["student", "is_used"],
                        name="api_cbtexam_student_3b207b_idx",
                    ),
                    models.Index(
                        fields=["exam_hall", "seat_number"],
                        name="api_cbtexam_exam_ha_8159fa_idx",
                    ),
                ],
            },
        ),
    ]
