# Generated by Django 5.2.7 on 2025-12-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_exam_allow_calculator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('student', 'subject', 'session', 'session_term')},
        ),
    ]
