# Generated by Django 5.2.7 on 2025-12-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_studentsubject_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.PositiveSmallIntegerField(default=0, verbose_name='punctuality')),
                ('mental_alertness', models.PositiveSmallIntegerField(default=0, verbose_name='mental alertness')),
                ('behavior', models.PositiveSmallIntegerField(default=0, verbose_name='behavior')),
                ('reliability', models.PositiveSmallIntegerField(default=0, verbose_name='reliability')),
                ('attentiveness', models.PositiveSmallIntegerField(default=0, verbose_name='attentiveness')),
                ('respect', models.PositiveSmallIntegerField(default=0, verbose_name='respect')),
                ('neatness', models.PositiveSmallIntegerField(default=0, verbose_name='neatness')),
                ('politeness', models.PositiveSmallIntegerField(default=0, verbose_name='politeness')),
                ('honesty', models.PositiveSmallIntegerField(default=0, verbose_name='honesty')),
                ('relationship_staff', models.PositiveSmallIntegerField(default=0, verbose_name='relationship with staff')),
                ('relationship_students', models.PositiveSmallIntegerField(default=0, verbose_name='relationship with students')),
                ('attitude_school', models.PositiveSmallIntegerField(default=0, verbose_name='attitude to school')),
                ('self_control', models.PositiveSmallIntegerField(default=0, verbose_name='self control')),
                ('handwriting', models.PositiveSmallIntegerField(default=0, verbose_name='handwriting')),
                ('reading', models.PositiveSmallIntegerField(default=0, verbose_name='reading')),
                ('verbal_fluency', models.PositiveSmallIntegerField(default=0, verbose_name='verbal fluency')),
                ('musical_skills', models.PositiveSmallIntegerField(default=0, verbose_name='musical skills')),
                ('creative_arts', models.PositiveSmallIntegerField(default=0, verbose_name='creative arts')),
                ('physical_education', models.PositiveSmallIntegerField(default=0, verbose_name='physical education')),
                ('general_reasoning', models.PositiveSmallIntegerField(default=0, verbose_name='general reasoning')),
                ('class_teacher_report', models.TextField(blank=True, verbose_name='class teacher report')),
                ('ict_report', models.TextField(blank=True, verbose_name='ict report')),
                ('principal_report', models.TextField(blank=True, verbose_name='principal report')),
                ('days_present', models.PositiveIntegerField(blank=True, null=True, verbose_name='days present')),
                ('days_absent', models.PositiveIntegerField(blank=True, null=True, verbose_name='days absent')),
                ('total_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='total days')),
                ('promoted_to', models.CharField(blank=True, max_length=100, verbose_name='promoted to')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='overall total score')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='average score')),
                ('class_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='class position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_reports', to='api.session', verbose_name='session')),
                ('session_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='term_reports', to='api.sessionterm', verbose_name='session term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='api.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Term Report',
                'verbose_name_plural': 'Term Reports',
                'ordering': ['student', 'session', 'session_term'],
                'unique_together': {('student', 'session', 'session_term')},
            },
        ),
    ]
