# Generated by Django 5.2.7 on 2025-12-29 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_termreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Purpose name (e.g., "Application Fee", "Exam Fee", "Tuition")', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique code (e.g., "admission", "cbt_exam", "school_fees")', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Purpose',
                'verbose_name_plural': 'Payment Purposes',
                'db_table': 'payment_purposes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cbtexamcode',
            name='access_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Code cannot be used after this datetime (for scheduled exams)', null=True, verbose_name='access end datetime'),
        ),
        migrations.AddField(
            model_name='cbtexamcode',
            name='access_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Code cannot be used before this datetime (for scheduled exams)', null=True, verbose_name='access start datetime'),
        ),
        migrations.AddField(
            model_name='student',
            name='application_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks completion of application steps: biodata, guardians, documents, payment', verbose_name='application checklist'),
        ),
        migrations.AddField(
            model_name='student',
            name='application_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the online application was submitted', null=True, verbose_name='application submitted at'),
        ),
        migrations.AddField(
            model_name='student',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Assigned when application is submitted', max_length=20, verbose_name='seat number'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_purpose',
            field=models.ForeignKey(blank=True, help_text='Purpose of this payment (admission, exam, tuition, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.paymentpurpose'),
        ),
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admission_open', models.BooleanField(default=False, help_text='Toggle to open/close admission portal', verbose_name='admission open')),
                ('admission_start_datetime', models.DateTimeField(blank=True, help_text='When admission opens', null=True, verbose_name='admission start datetime')),
                ('admission_end_datetime', models.DateTimeField(blank=True, help_text='When admission closes', null=True, verbose_name='admission end datetime')),
                ('application_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Application fee amount', max_digits=10, verbose_name='application fee amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_settings_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_settings', to='api.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'Admission Settings',
                'verbose_name_plural': 'Admission Settings',
                'ordering': ['-updated_at'],
                'unique_together': {('school',)},
            },
        ),
        migrations.CreateModel(
            name='ApplicationSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Unique seat number assigned to applicant', max_length=20)),
                ('application_number', models.CharField(help_text='Application number from student record', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated application slip PDF', null=True, upload_to='application_slips/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_slip', to='api.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Application Slip',
                'verbose_name_plural': 'Application Slips',
                'db_table': 'application_slips',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['seat_number'], name='application_seat_nu_f89473_idx'), models.Index(fields=['application_number'], name='application_applica_e2d608_idx')],
            },
        ),
    ]
