# Generated by Django 5.2.7 on 2026-01-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_paymentpurpose_cbtexamcode_access_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicationslip',
            name='application_seat_nu_f89473_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationslip',
            name='application_applica_e2d608_idx',
        ),
        migrations.AddField(
            model_name='applicationslip',
            name='exam_hall',
            field=models.ForeignKey(blank=True, help_text='Exam hall assigned for entrance examination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_slips', to='api.examhall', verbose_name='exam hall'),
        ),
        migrations.AlterField(
            model_name='applicationslip',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, help_text='Physical seat number in exam hall (e.g., 1, 2, 3, 15)', null=True),
        ),
        migrations.AddIndex(
            model_name='applicationslip',
            index=models.Index(fields=['exam_hall', 'seat_number'], name='application_exam_ha_d155ba_idx'),
        ),
    ]
