# Generated by Django 5.2.7 on 2026-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_applicationslip_application_seat_nu_f89473_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicationslip',
            name='application_exam_ha_d155ba_idx',
        ),
        migrations.RemoveField(
            model_name='applicationslip',
            name='exam_hall',
        ),
        migrations.RemoveField(
            model_name='applicationslip',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='applicationslip',
            name='screening_date',
            field=models.DateField(blank=True, help_text='Scheduled date for screening/interview', null=True),
        ),
    ]
