# Generated by Django 5.2.7 on 2026-01-06 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_applicationslip_application_exam_ha_d155ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_class',
            field=models.ForeignKey(blank=True, help_text='Target class for admission exams (e.g., JSS1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_exams', to='api.class', verbose_name='exam class'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_applicant_exam',
            field=models.BooleanField(default=False, help_text='Is this an admission exam for new applicants?', verbose_name='is applicant exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_selection_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to randomly select from the bank (e.g., 50)', null=True, verbose_name='question selection count'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject for academic exams (leave blank for general admission exams)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.subject', verbose_name='subject'),
        ),
    ]
