# Generated by Django 5.2.7 on 2026-01-06 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_exam_exam_class_exam_is_applicant_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 1st Period, Long Break', max_length=50, verbose_name='period name')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('period_type', models.CharField(choices=[('lesson', 'Lesson'), ('break', 'Break'), ('assembly', 'Assembly'), ('other', 'Other')], default='lesson', max_length=20, verbose_name='period type')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordering for display (1, 2, 3...)', verbose_name='order')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='api.school', verbose_name='school')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['school', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.class', verbose_name='class')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_entries', to='api.period')),
                ('session_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.sessionterm', verbose_name='session term')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_occurrences', to='api.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher for this specific lesson. Defaults to subject teacher if blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetabled_lessons', to='api.staff')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['day_of_week', 'period__order'],
                'unique_together': {('session_term', 'class_model', 'day_of_week', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.class')),
                ('session_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionterm')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_taken', to=settings.AUTH_USER_MODEL)),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_taken', to='api.timetableentry')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-marked_at'],
                'unique_together': {('class_model', 'date', 'timetable_entry')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10, verbose_name='status')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='remark')),
                ('time_marked', models.TimeField(auto_now_add=True, verbose_name='time marked')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.attendancerecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='api.student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance',
                'unique_together': {('attendance_record', 'student')},
            },
        ),
    ]
