# Generated by Django 5.2.10 on 2026-01-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_period_timetableentry_attendancerecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="ca_max_score",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Maximum score for Continuous Assessment (e.g., 40)",
                verbose_name="CA max score",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="exam_max_score",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Maximum score for Examination (e.g., 60)",
                verbose_name="Exam max score",
            ),
        ),
    ]
