# Generated by Django 5.2.10 on 2026-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_school_ca_max_score_school_exam_max_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="termreport",
            name="cumulative_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average of all term averages for the session (only for 3rd term)",
                max_digits=5,
                null=True,
                verbose_name="cumulative average",
            ),
        ),
    ]
