# Generated by Django 5.2.10 on 2026-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_termreport_cumulative_average"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="principal_remark",
            field=models.CharField(
                blank=True,
                help_text="Default remark for principal if average falls in this range",
                max_length=255,
                verbose_name="principal remark",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="teacher_remark",
            field=models.CharField(
                blank=True,
                help_text="Default remark for class teacher if average falls in this range",
                max_length=255,
                verbose_name="teacher remark",
            ),
        ),
    ]
