# Generated by Django 5.2.10 on 2026-01-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_grade_principal_remark_grade_teacher_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="grade_level",
            field=models.CharField(
                blank=True,
                help_text='Grouping for arms (e.g. "JSS 1" for JSS 1A, JSS 1B)',
                max_length=50,
                verbose_name="grade level",
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="grade_position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="position in set"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="total_students",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="total students in arm"
            ),
        ),
        migrations.AddField(
            model_name="termreport",
            name="total_students_grade",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="total students in set"
            ),
        ),
        migrations.AlterField(
            model_name="termreport",
            name="class_position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="position in arm"
            ),
        ),
    ]
