# Generated by Django 5.2.10 on 2026-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_class_grade_level_termreport_grade_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Auto-generated on acceptance (Format: YYYYMMDD + Serial)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="admission number",
            ),
        ),
    ]
