# Generated by Django 5.2.10 on 2026-01-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_student_admission_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubject",
            name="highest_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Highest score achieved in this class for this subject",
                max_digits=5,
                null=True,
                verbose_name="highest score in class",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="lowest_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Lowest score achieved in this class for this subject",
                max_digits=5,
                null=True,
                verbose_name="lowest score in class",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="subject_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average score of students in this class for this subject",
                max_digits=5,
                null=True,
                verbose_name="class average",
            ),
        ),
    ]
