# Generated by Django 5.2.10 on 2026-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_studentsubject_highest_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='ict_remark',
            field=models.CharField(blank=True, help_text='Default remark for ICT department if average falls in this range', max_length=255, verbose_name='ICT remark'),
        ),
    ]
