# Generated by Django 5.2.10 on 2026-01-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_grade_ict_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="option_a_image",
            field=models.ImageField(blank=True, null=True, upload_to="cbt/options/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b_image",
            field=models.ImageField(blank=True, null=True, upload_to="cbt/options/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c_image",
            field=models.ImageField(blank=True, null=True, upload_to="cbt/options/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d_image",
            field=models.ImageField(blank=True, null=True, upload_to="cbt/options/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_e_image",
            field=models.ImageField(blank=True, null=True, upload_to="cbt/options/"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for the question",
                null=True,
                upload_to="cbt/questions/",
                verbose_name="question image",
            ),
        ),
    ]
