# Generated by Django 5.2.10 on 2026-01-21 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_question_option_a_image_question_option_b_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., First Term Exams, JS3 Mock Exams",
                        max_length=100,
                        verbose_name="schedule name",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("exam", "Examination"),
                            ("test", "Test/Quiz"),
                            ("event", "School Event"),
                            ("general", "General Schedule"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="schedule type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="api.sessionterm",
                        verbose_name="session term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Mathematics Exam, Morning Assembly",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_exam",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a specific CBT Exam configuration if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="api.exam",
                        verbose_name="linked exam",
                    ),
                ),
                (
                    "linked_subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a subject for display purposes (e.g. Revision)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="api.subject",
                        verbose_name="linked subject",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="api.schedule",
                        verbose_name="schedule",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_schedules",
                        to="api.staff",
                        verbose_name="supervisor/invigilator",
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(
                        help_text="Classes this entry applies to",
                        related_name="schedule_entries",
                        to="api.class",
                        verbose_name="target classes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Entry",
                "verbose_name_plural": "Schedule Entries",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["date", "start_time"],
                        name="api_schedul_date_183a6e_idx",
                    )
                ],
            },
        ),
    ]
