# Generated by Django 5.2.10 on 2026-01-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_schedule_scheduleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_members",
                to="api.school",
            ),
        ),
    ]
