# Generated by Django 5.2.10 on 2026-01-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_staff_school"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Schedule", "verbose_name_plural": "Schedules"},
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="session_term",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_date",
        ),
    ]
