# Generated by Django 5.2.10 on 2026-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_alter_schedule_options_remove_schedule_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="description",
        ),
        migrations.AddField(
            model_name="schedule",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
    ]
