# Generated by Django 5.2.10 on 2026-01-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_remove_schedule_description_schedule_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Fees that must be paid before this fee can be paid",
                related_name="required_by",
                to="api.feetype",
            ),
        ),
    ]
