# Generated by Django 5.2.10 on 2026-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_feetype_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="active_terms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Terms in which this fee is available for payment",
                related_name="active_fees",
                to="api.sessionterm",
            ),
        ),
    ]
