# Generated by Django 5.2.10 on 2026-01-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_feetype_active_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "paystack_customer_code",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Virtual Account Number", max_length=20
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="api.staff",
                    ),
                ),
            ],
            options={
                "db_table": "staff_wallets",
            },
        ),
    ]
