# Generated by Django 5.2.10 on 2026-01-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_staffwallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanTenure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. 6 Months Plan", max_length=100),
                ),
                ("duration_months", models.PositiveIntegerField()),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest rate (percentage)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "loan_tenures",
                "ordering": ["duration_months"],
            },
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="tenure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="api.loantenure",
            ),
        ),
    ]
