# Generated by Django 5.2.10 on 2026-01-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_loantenure_loanapplication_tenure"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeOfWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("1st Term", "1st Term"),
                            ("2nd Term", "2nd Term"),
                            ("3rd Term", "3rd Term"),
                        ],
                        max_length=20,
                        verbose_name="term",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(
                        help_text="Week number (1-15)", verbose_name="week number"
                    ),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="topic")),
                (
                    "learning_objectives",
                    models.TextField(
                        blank=True,
                        help_text="What students should be able to do by the end of the week",
                        verbose_name="learning objectives",
                    ),
                ),
                (
                    "resources",
                    models.TextField(
                        blank=True,
                        help_text="Teaching resources, links, or textbook references",
                        verbose_name="resources",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes_of_work",
                        to="api.subject",
                        verbose_name="subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheme of Work",
                "verbose_name_plural": "Schemes of Work",
                "ordering": ["subject", "term", "week_number"],
                "unique_together": {("subject", "term", "week_number")},
            },
        ),
    ]
