# Generated by Django 5.2.10 on 2026-01-26 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_schemeofwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="schemeofwork",
            name="topic_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to existing topic",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schemes_of_work",
                to="api.topic",
                verbose_name="topic reference",
            ),
        ),
        migrations.AlterField(
            model_name="schemeofwork",
            name="topic",
            field=models.CharField(
                blank=True,
                help_text="Legacy/Fallback topic name",
                max_length=200,
                verbose_name="topic",
            ),
        ),
    ]
