# Generated by Django 5.2.10 on 2026-01-27 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_schemeofwork_topic_model_alter_schemeofwork_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_code", models.CharField(max_length=20)),
                ("account_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=200)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="api.staff",
                    ),
                ),
            ],
            options={
                "db_table": "staff_beneficiaries",
                "ordering": ["-created_at"],
                "unique_together": {("staff", "account_number", "bank_code")},
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("account_number", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processed", "Processed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="api.staff",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawal_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="withdrawal__status_0dc12a_idx"
                    )
                ],
            },
        ),
    ]
