# Generated by Django 5.2.10 on 2026-01-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_staffbeneficiary_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="staff_children_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discounted amount for staff children. Leave blank for no discount.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select students who are children of this staff member",
                related_name="staff_parents",
                to="api.student",
            ),
        ),
    ]
