# Generated by Django 5.2.10 on 2026-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_feetype_staff_children_amount_staff_children"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="reference_number",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
