# Generated by Django 5.2.10 on 2026-01-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_withdrawalrequest_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffbeneficiary",
            name="paystack_recipient_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="transfer_code",
            field=models.CharField(
                blank=True, help_text="Paystack Transfer Code", max_length=50, null=True
            ),
        ),
    ]
