# Generated by Django 5.2.10 on 2026-01-29 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_staffbeneficiary_paystack_recipient_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("funding", "Wallet Funding"),
                            ("withdrawal", "Withdrawal"),
                            ("loan_disbursement", "Loan Disbursement"),
                            ("loan_repayment", "Loan Repayment"),
                            ("salary", "Salary Payment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.staffwallet",
                    ),
                ),
            ],
            options={
                "db_table": "staff_wallet_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="staff_walle_referen_7c9c2f_idx"
                    ),
                    models.Index(
                        fields=["category"], name="staff_walle_categor_cb240b_idx"
                    ),
                ],
            },
        ),
    ]
