# Generated by Django 5.2.10 on 2026-01-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_staffwallettransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="withdrawalrequest",
            name="staff",
        ),
        migrations.AddField(
            model_name="staffwallettransaction",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="staffwallettransaction",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="staffwallettransaction",
            name="transfer_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack Transfer Code",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="staffwallettransaction",
            index=models.Index(fields=["status"], name="staff_walle_status_0b1aed_idx"),
        ),
        migrations.DeleteModel(
            name="WithdrawalRequest",
        ),
    ]
