# Generated by Django 5.2.10 on 2026-02-03 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_leaverequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="answers")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="score",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Late"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="feedback")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="api_assignm_subject_69aa08_idx",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="api_assignm_status_762ce4_idx",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
        migrations.AddField(
            model_name="assignment",
            name="class_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="api.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="is published"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_created",
                to="api.staff",
                verbose_name="staff",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="questions",
            field=models.ManyToManyField(
                related_name="assignments", to="api.question", verbose_name="questions"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="api.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="api.assignment",
                verbose_name="assignment",
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to="api.student",
                verbose_name="student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment", "student")},
        ),
    ]
