# Generated by Django 5.2.10 on 2026-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_assignmentsubmission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentsubmission",
            options={
                "ordering": ["-submitted_at", "-created_at"],
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
            },
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="marks",
            field=models.JSONField(blank=True, default=dict, verbose_name="marks"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("true_false", "True/False"),
                    ("essay", "Essay"),
                    ("fill_blank", "Fill in the Blank"),
                    ("short_answer", "Short Answer"),
                    ("file_upload", "File Upload"),
                ],
                default="multiple_choice",
                max_length=20,
                verbose_name="question type",
            ),
        ),
    ]
