# Generated by Django 5.2.10 on 2026-02-03 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_assignmentsubmission_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Required for Email templates",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Use {{ variable }} for dynamic content"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description of what this template is for",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "communication_templates",
                "ordering": ["name"],
            },
        ),
    ]
