# Generated by Django 5.2.10 on 2026-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_biometricstation"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometric",
            name="right_thumb_template",
            field=models.TextField(
                blank=True, null=True, verbose_name="right thumb template"
            ),
        ),
    ]
