# Generated by Django 5.2.10 on 2026-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_biometric_right_thumb_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometric",
            name="left_index",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="biometrics/%Y/%m/%d/",
                verbose_name="left index",
            ),
        ),
        migrations.AddField(
            model_name="biometric",
            name="left_index_template",
            field=models.TextField(
                blank=True, null=True, verbose_name="left index template"
            ),
        ),
        migrations.AddField(
            model_name="biometric",
            name="left_thumb_template",
            field=models.TextField(
                blank=True, null=True, verbose_name="left thumb template"
            ),
        ),
        migrations.AddField(
            model_name="biometric",
            name="right_index",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="biometrics/%Y/%m/%d/",
                verbose_name="right index",
            ),
        ),
        migrations.AddField(
            model_name="biometric",
            name="right_index_template",
            field=models.TextField(
                blank=True, null=True, verbose_name="right index template"
            ),
        ),
    ]
