# Generated by Django 5.2.10 on 2026-02-20 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_biometric_left_index_biometric_left_index_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionterm",
            name="registration_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline for normal subject registration",
                null=True,
                verbose_name="registration deadline",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="is_late_registration",
            field=models.BooleanField(
                default=False, verbose_name="is late registration"
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="late_fee_paid",
            field=models.BooleanField(default=False, verbose_name="late fee paid"),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="objective_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="CBT Objective score",
                max_digits=5,
                null=True,
                verbose_name="objective score",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="theory_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Theory/Written examination score (max 40)",
                max_digits=5,
                null=True,
                verbose_name="theory score",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("exam", "Examination"),
                    ("test", "Test/Quiz"),
                    ("cbt_exam", "CBT Examination"),
                    ("event", "School Event"),
                    ("general", "General Schedule"),
                ],
                default="general",
                max_length=20,
                verbose_name="schedule type",
            ),
        ),
        migrations.CreateModel(
            name="GuardianMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_messages",
                        to="api.guardian",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_guardian_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_messages",
                        to="api.student",
                    ),
                ),
            ],
            options={
                "db_table": "guardian_messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
