# Generated by Django 5.2.10 on 2026-02-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_sessionterm_registration_deadline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_download_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        help_text="Fee charged for re-downloading a result after the first time",
                        max_digits=10,
                        verbose_name="result download fee",
                    ),
                ),
                (
                    "show_announcement",
                    models.BooleanField(
                        default=False, verbose_name="show announcement"
                    ),
                ),
                (
                    "announcement_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="announcement title"
                    ),
                ),
                (
                    "announcement_message",
                    models.TextField(blank=True, verbose_name="announcement message"),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(default=False, verbose_name="maintenance mode"),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        default="System is under maintenance.",
                        verbose_name="maintenance message",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.AddField(
            model_name="termreport",
            name="download_count",
            field=models.PositiveIntegerField(default=0, verbose_name="download count"),
        ),
        migrations.AddField(
            model_name="termreport",
            name="first_downloaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="first downloaded at"
            ),
        ),
    ]
