# Generated by Django 5.2.10 on 2026-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_systemsetting_termreport_download_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="disable_staff_login",
            field=models.BooleanField(
                default=False, verbose_name="disable staff login"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="disable_student_login",
            field=models.BooleanField(
                default=False, verbose_name="disable student login"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="staff_maintenance_message",
            field=models.TextField(
                default="Staff portal is temporarily unavailable.",
                verbose_name="staff maintenance message",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="student_maintenance_message",
            field=models.TextField(
                default="Student portal is temporarily unavailable.",
                verbose_name="student maintenance message",
            ),
        ),
    ]
