# Generated by Django 5.2.10 on 2026-02-25 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_systemsetting_disable_staff_login_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentpurpose",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="admissionsettings",
            name="admission_end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="admission end datetime"
            ),
        ),
        migrations.AlterField(
            model_name="admissionsettings",
            name="admission_start_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="admission start datetime"
            ),
        ),
        migrations.AlterField(
            model_name="admissionsettings",
            name="application_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="application fee amount",
            ),
        ),
        migrations.AlterField(
            model_name="admissionsettings",
            name="is_admission_open",
            field=models.BooleanField(default=False, verbose_name="admission open"),
        ),
        migrations.AlterField(
            model_name="applicationslip",
            name="application_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="applicationslip",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="application_slips/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="applicationslip",
            name="screening_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="access_end_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="access end datetime"
            ),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="access_start_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="access start datetime"
            ),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="code",
            field=models.CharField(max_length=6, unique=True, verbose_name="passcode"),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cbt_codes",
                to="api.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="exam_hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cbt_codes",
                to="api.examhall",
                verbose_name="exam hall",
            ),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="used"),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="seat_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="seat number"
            ),
        ),
        migrations.AlterField(
            model_name="cbtexamcode",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cbt_exam_codes",
                to="api.student",
                verbose_name="student",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="allow_calculator",
            field=models.BooleanField(default=False, verbose_name="allow calculator"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="allow_review",
            field=models.BooleanField(default=True, verbose_name="allow review"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="duration_minutes",
            field=models.PositiveIntegerField(verbose_name="duration (minutes)"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_exams",
                to="api.class",
                verbose_name="exam class",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="exam ID",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="instructions",
            field=models.TextField(blank=True, null=True, verbose_name="instructions"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_applicant_exam",
            field=models.BooleanField(default=False, verbose_name="is applicant exam"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="pass_mark",
            field=models.PositiveIntegerField(verbose_name="pass mark"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="question_selection_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="question selection count"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="exams",
                to="api.question",
                verbose_name="questions",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="show_results_immediately",
            field=models.BooleanField(
                default=False, verbose_name="show results immediately"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="shuffle_options",
            field=models.BooleanField(default=True, verbose_name="shuffle options"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="shuffle_questions",
            field=models.BooleanField(default=True, verbose_name="shuffle questions"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="api.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="title",
            field=models.CharField(max_length=200, verbose_name="exam title"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="api.topic", verbose_name="topics"
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="total_marks",
            field=models.PositiveIntegerField(verbose_name="total marks"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="total_questions",
            field=models.PositiveIntegerField(verbose_name="total questions"),
        ),
        migrations.AlterField(
            model_name="examhall",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="examhall",
            name="number_of_seats",
            field=models.PositiveIntegerField(verbose_name="number of seats"),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="installment_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="api.paymentpurpose",
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_payments",
                to="api.session",
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="session_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fee_payments",
                to="api.sessionterm",
            ),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="active_terms",
            field=models.ManyToManyField(
                blank=True, related_name="active_fees", to="api.sessionterm"
            ),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="applicable_classes",
            field=models.ManyToManyField(
                blank=True, related_name="fee_types", to="api.class"
            ),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="is_mandatory",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="is_recurring_per_term",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="max_installments",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="required_by", to="api.feetype"
            ),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="staff_children_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_description",
            field=models.CharField(max_length=100, verbose_name="grade description"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_letter",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                ],
                max_length=1,
                unique=True,
                verbose_name="grade letter",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_name",
            field=models.CharField(max_length=20, verbose_name="grade name"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="ict_remark",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ICT remark"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="max_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="maximum score"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="min_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="minimum score"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="order",
            field=models.PositiveSmallIntegerField(
                editable=False, verbose_name="display order"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="principal_remark",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="principal remark"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="teacher_remark",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="teacher remark"
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="purpose",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="repayment_period_months",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="paymentpurpose",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentpurpose",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="period",
            name="name",
            field=models.CharField(max_length=50, verbose_name="period name"),
        ),
        migrations.AlterField(
            model_name="period",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(verbose_name="correct answer"),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True, verbose_name="explanation"),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AlterField(
            model_name="question",
            name="marks",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="marks"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cbt/questions/",
                verbose_name="question image",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="question text"),
        ),
        migrations.AlterField(
            model_name="question",
            name="topic_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.topic",
                verbose_name="topic",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="usage_count",
            field=models.PositiveIntegerField(default=0, verbose_name="usage count"),
        ),
        migrations.AlterField(
            model_name="salarygrade",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="linked_exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_entries",
                to="api.exam",
                verbose_name="linked exam",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="linked_subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_entries",
                to="api.subject",
                verbose_name="linked subject",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="target_classes",
            field=models.ManyToManyField(
                related_name="schedule_entries",
                to="api.class",
                verbose_name="target classes",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="schemeofwork",
            name="learning_objectives",
            field=models.TextField(blank=True, verbose_name="learning objectives"),
        ),
        migrations.AlterField(
            model_name="schemeofwork",
            name="resources",
            field=models.TextField(blank=True, verbose_name="resources"),
        ),
        migrations.AlterField(
            model_name="schemeofwork",
            name="topic",
            field=models.CharField(blank=True, max_length=200, verbose_name="topic"),
        ),
        migrations.AlterField(
            model_name="schemeofwork",
            name="topic_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schemes_of_work",
                to="api.topic",
                verbose_name="topic reference",
            ),
        ),
        migrations.AlterField(
            model_name="schemeofwork",
            name="week_number",
            field=models.PositiveIntegerField(verbose_name="week number"),
        ),
        migrations.AlterField(
            model_name="sessionterm",
            name="registration_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="registration deadline"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="assigned_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_staff_members",
                to="api.class",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="children",
            field=models.ManyToManyField(
                blank=True, related_name="staff_parents", to="api.student"
            ),
        ),
        migrations.AlterField(
            model_name="staffeducation",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ond", "OND"),
                    ("hnd", "HND"),
                    ("nce", "NCE"),
                    ("bsc", "B.Sc"),
                    ("bed", "B.Ed"),
                    ("msc", "M.Sc"),
                    ("med", "M.Ed"),
                    ("phd", "Ph.D"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffwallettransaction",
            name="transfer_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="answer_text",
            field=models.TextField(verbose_name="answer text"),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="question_number",
            field=models.PositiveSmallIntegerField(verbose_name="question number"),
        ),
        migrations.AlterField(
            model_name="studentexam",
            name="question_order",
            field=models.JSONField(
                blank=True, null=True, verbose_name="question order"
            ),
        ),
        migrations.AlterField(
            model_name="studentexam",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="score",
            ),
        ),
        migrations.AlterField(
            model_name="studentexam",
            name="time_remaining_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="time remaining (seconds)"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="ca_max",
            field=models.DecimalField(
                decimal_places=2,
                default=40,
                max_digits=5,
                verbose_name="CA maximum score",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="subject code"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="api.department",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="exam_max",
            field=models.DecimalField(
                decimal_places=2,
                default=60,
                max_digits=5,
                verbose_name="Exam maximum score",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="result_download_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                max_digits=10,
                verbose_name="result download fee",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetabled_lessons",
                to="api.staff",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=200, verbose_name="topic name"),
        ),
    ]
