# Generated by Django 5.2.10 on 2026-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_alter_paymentpurpose_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="late_subject_registration_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=500.0,
                max_digits=10,
                verbose_name="late subject registration fee",
            ),
        ),
    ]
