# Generated by Django 5.2.12 on 2026-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_systemsetting_late_subject_registration_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionterm",
            name="is_subject_registration_open",
            field=models.BooleanField(
                default=False, verbose_name="subject registration open"
            ),
        ),
    ]
