# Generated by Django 5.2.12 on 2026-03-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_gallerygroup_galleryimage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gallerygroup",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="gallerygroup",
            name="school",
        ),
    ]
