# Generated by Django 5.2.12 on 2026-03-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_alter_gallerygroup_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("1st Term", "1st Term"),
                            ("2nd Term", "2nd Term"),
                            ("3rd Term", "3rd Term"),
                        ],
                        max_length=20,
                        verbose_name="term",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="past_questions/", verbose_name="file"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "class_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_questions",
                        to="api.class",
                        verbose_name="class",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="past_questions",
                        to="api.session",
                        verbose_name="session",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_questions",
                        to="api.subject",
                        verbose_name="subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_past_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Past Question",
                "verbose_name_plural": "Past Questions",
                "ordering": ["-created_at"],
            },
        ),
    ]
