# Generated by Django 5.2.12 on 2026-03-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_pastquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Objectives", "Objectives"),
                    ("Theory", "Theory"),
                    ("Practical", "Practical"),
                ],
                default="Objectives",
                max_length=20,
                verbose_name="question type",
            ),
        ),
    ]
