# Generated by Django 5.2.12 on 2026-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_systemsetting_result_pin_price_resultpin"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="applicable_students",
            field=models.ManyToManyField(
                blank=True, related_name="penalty_fees", to="api.student"
            ),
        ),
        migrations.AddField(
            model_name="feetype",
            name="is_penalty",
            field=models.BooleanField(
                default=False,
                help_text="If true, unpaid fee blocks student portal access",
            ),
        ),
        migrations.AddField(
            model_name="feetype",
            name="penalty_reason",
            field=models.TextField(
                blank=True, help_text="Reason for the penalty (e.g. Broken window)"
            ),
        ),
    ]
