# Generated by Django 5.2.13 on 2026-05-01 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_feetype_applicable_students_feetype_is_penalty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalExamBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('short_name', models.CharField(max_length=20, verbose_name='short name')),
            ],
            options={
                'verbose_name': 'External Exam Body',
                'verbose_name_plural': 'External Exam Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='external_exam_access_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='external exam access fee'),
        ),
        migrations.CreateModel(
            name='ExternalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('sitting', models.CharField(blank=True, choices=[('may_june', 'May/June'), ('nov_dec', 'Nov/Dec'), ('annual', 'Annual')], max_length=20, verbose_name='sitting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_exams', to='api.class', verbose_name='applicable class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_exams', to='api.staff', verbose_name='created by')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='api.externalexambody', verbose_name='exam body')),
            ],
            options={
                'verbose_name': 'External Exam',
                'verbose_name_plural': 'External Exams',
                'ordering': ['-year', 'body'],
                'unique_together': {('body', 'year', 'sitting', 'applicable_class')},
            },
        ),
        migrations.CreateModel(
            name='ExternalExamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='api.externalexam', verbose_name='exam')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_exam_access', to='api.feepayment', verbose_name='payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_exam_accesses', to='api.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'External Exam Access',
                'verbose_name_plural': 'External Exam Accesses',
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ExternalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='external_exams/results/', verbose_name='result file')),
                ('grades', models.JSONField(blank=True, null=True, verbose_name='grades')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.externalexam', verbose_name='exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_exam_results', to='api.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'External Exam Result',
                'verbose_name_plural': 'External Exam Results',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
