# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_externalexambody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_ca_score_editing',
            field=models.BooleanField(default=True, verbose_name='allow CA score editing'),
        ),
    ]
