# Generated by Django 5.2.13 on 2026-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0084_systemsetting_require_result_entry_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="wants_mock_exam",
            field=models.BooleanField(
                default=False,
                help_text="Whether the applicant wants to participate in the optional mock exam",
                verbose_name="wants to do mock exam",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="mock_exam_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=2000.0,
                max_digits=10,
                verbose_name="mock exam fee",
            ),
        ),
    ]
