# Generated by Django 5.2.13 on 2026-05-06 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0085_student_wants_mock_exam_systemsetting_mock_exam_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="account_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="account name"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="account number"
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="bank name"
            ),
        ),
        migrations.CreateModel(
            name="AdmissionBankTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference"
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        upload_to="payment_screenshots/%Y/%m/%d/",
                        verbose_name="screenshot",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verified at"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transfers",
                        to="api.student",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_admission_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Bank Transfer",
                "verbose_name_plural": "Admission Bank Transfers",
                "db_table": "admission_bank_transfers",
                "ordering": ["-created_at"],
            },
        ),
    ]
