# Generated by Django 5.2.13 on 2026-05-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0087_systemsetting_show_admission_exam_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_multi_subject",
            field=models.BooleanField(default=False, verbose_name="is multi-subject"),
        ),
        migrations.CreateModel(
            name="ExamSubjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_groups",
                        to="api.exam",
                        verbose_name="exam",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="exam_groups",
                        to="api.question",
                        verbose_name="questions",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_groups",
                        to="api.subject",
                        verbose_name="subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Subject Group",
                "verbose_name_plural": "Exam Subject Groups",
                "ordering": ["order", "id"],
                "unique_together": {("exam", "subject")},
            },
        ),
    ]
