# Generated by Django 5.2.13 on 2026-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_exam_is_multi_subject_examsubjectgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
