# Generated by Django 5.2.13 on 2026-05-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_exam_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="slug"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("student", "Student"),
                            ("all", "All Users"),
                        ],
                        default="admin",
                        max_length=20,
                        verbose_name="audience",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("coming_soon", "Coming Soon"),
                            ("beta", "Beta"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="Sparkles",
                        help_text='lucide-react icon component name, e.g. "Sparkles", "Bot"',
                        max_length=50,
                        verbose_name="icon name",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Frontend route this feature opens, or empty if it lives inside another page",
                        max_length=200,
                        verbose_name="route",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "AI Feature",
                "verbose_name_plural": "AI Features",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["audience", "is_active"],
                        name="api_aifeatu_audienc_2e6908_idx",
                    )
                ],
            },
        ),
    ]
