# Generated by Codex on 2026-05-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_aifeature"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMessageDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")],
                        max_length=10,
                    ),
                ),
                (
                    "target_group",
                    models.CharField(
                        choices=[
                            ("all_students", "All Students"),
                            ("specific_class", "Specific Class"),
                            ("all_staff", "All Staff"),
                            ("teaching_staff", "Teaching Staff"),
                            ("non_teaching_staff", "Non-Teaching Staff"),
                            ("custom", "Custom Recipients"),
                        ],
                        max_length=30,
                    ),
                ),
                ("student_ids", models.JSONField(blank=True, default=list)),
                ("custom_recipients", models.JSONField(blank=True, default=list)),
                ("prompt", models.TextField()),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("ai_model", models.CharField(blank=True, max_length=80)),
                ("send_summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_message_drafts_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_message_drafts",
                        to="api.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_message_drafts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_message_drafts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_message_drafts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_message__status_a8f4c1_idx",
                    ),
                    models.Index(
                        fields=["channel", "target_group"],
                        name="ai_message__channel_946ec4_idx",
                    ),
                ],
            },
        ),
    ]
