# Generated by Codex on 2026-05-10

from django.db import migrations


def seed_message_drafts_feature(apps, schema_editor):
    AIFeature = apps.get_model("api", "AIFeature")
    AIFeature.objects.get_or_create(
        slug="message-draft-approvals",
        defaults={
            "name": "AI Communications",
            "description": (
                "Draft school emails or SMS from a simple instruction, review the "
                "AI copy, and send only after admin approval."
            ),
            "audience": "admin",
            "status": "available",
            "icon": "MailCheck",
            "route": "/school-admin/communications?ai=drafts",
            "is_active": True,
            "order": 2,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0091_aimessagedraft"),
    ]

    operations = [
        migrations.RunPython(seed_message_drafts_feature, migrations.RunPython.noop),
    ]
