# Generated by Codex on 2026-05-10

from django.db import migrations


def update_ai_communications_route(apps, schema_editor):
    AIFeature = apps.get_model("api", "AIFeature")
    AIFeature.objects.filter(slug="message-draft-approvals").update(
        name="AI Communications",
        route="/school-admin/communications?ai=drafts",
        icon="MailCheck",
        status="available",
        audience="admin",
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_seed_ai_message_drafts_feature"),
    ]

    operations = [
        migrations.RunPython(update_ai_communications_route, migrations.RunPython.noop),
    ]
