# Generated by Django 5.2.13 on 2026-05-10 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0093_update_ai_communications_feature_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("update_fee_type_amount", "Update Fee Type Amount"),
                            ("update_record_fields", "Update Record Fields"),
                        ],
                        max_length=80,
                        verbose_name="action type",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=120, verbose_name="label"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="summary")),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="approval payload"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="approval result"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, default=list, verbose_name="changes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("reverted", "Reverted"),
                            ("failed", "Failed"),
                        ],
                        default="approved",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="approved at"),
                ),
                (
                    "reverted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reverted at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions_reverted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Action Log",
                "verbose_name_plural": "AI Action Logs",
                "ordering": ["-approved_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "approved_at"],
                        name="api_aiactio_status_ba908c_idx",
                    ),
                    models.Index(
                        fields=["action_type", "approved_at"],
                        name="api_aiactio_action__a9b3a8_idx",
                    ),
                ],
            },
        ),
    ]
