# Generated by Django 5.2.13 on 2026-05-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_ai_action_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessagedraft",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
