# Generated by Django 5.2.13 on 2026-05-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_studentaitutorchat_studentaitutormessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="ai_disabled_message",
            field=models.TextField(
                default="AI features are temporarily unavailable for students. Please check back later.",
                verbose_name="AI disabled message",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="is_ai_enabled",
            field=models.BooleanField(default=True, verbose_name="enable student AI"),
        ),
    ]
