# Generated by Django 5.2.13 on 2026-05-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0097_systemsetting_ai_disabled_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsetting",
            name="is_ai_enabled",
            field=models.BooleanField(default=False, verbose_name="enable student AI"),
        ),
    ]
