# Generated by Django 5.2.13 on 2026-05-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0098_alter_systemsetting_is_ai_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionterm",
            name="rankings_calculated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="rankings last calculated at"
            ),
        ),
    ]
