# Generated by Django 5.2.13 on 2026-05-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0100_staff_documents_and_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("nin", "National Identification Number (NIN)"),
                    ("birth_certificate", "Birth Certificate"),
                    ("primary_certificate", "Primary School Certificate"),
                    ("bece_certificate", "BECE Certificate"),
                    ("previous_school_cert", "Previous School Certificate"),
                    ("passport", "Passport Photograph"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="document type",
            ),
        ),
    ]
