# Generated by Django 5.2.13 on 2026-05-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0101_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffchangerequest",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_requests",
                to="api.staffeducation",
            ),
        ),
        migrations.AddField(
            model_name="staffeducation",
            name="verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffeducation",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffeducation",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_education_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffchangerequest",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("profile_field", "Profile Field"),
                    ("document_upload", "Document Uploaded"),
                    ("document_replace", "Document Replaced"),
                    ("document_delete", "Document Deleted"),
                    ("education_create", "Education Record Added"),
                    ("education_update", "Education Record Updated"),
                    ("education_delete", "Education Record Deleted"),
                ],
                max_length=30,
            ),
        ),
    ]
