# Generated by Django 5.1.5 on 2025-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
