# Generated by Django 5.2.1 on 2025-06-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_biodata_address_alter_biodata_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='guardians_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='guardians_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='guardians_country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='guardians_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
