"""
Django settings for serverConfig project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

HCTI_USER_ID = os.getenv('HCTI_USER_ID')
HCTI_API_KEY = os.getenv('HCTI_API_KEY')
EXTERNAL_RENDER_API_KEY = os.getenv('EXTERNAL_RENDER_API_KEY')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Get environment mode
ENV = os.getenv('ENV', 'development')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

if ENV == 'production' and not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in production environment!")

if not SECRET_KEY:
    SECRET_KEY = 'django-insecure-dev-key-do-not-use-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []

# Allow ngrok URLs for testing webhooks
ALLOWED_HOSTS.extend(['.ngrok-free.dev', '.ngrok.io', 'interavailable-lexi-instigative.ngrok-free'])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "dj_rest_auth",
    
    # Local apps
    "api",
]

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.CsrfEnforcedSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# dj-rest-auth Configuration (no registration, no social auth)
REST_AUTH = {
    'SESSION_LOGIN': True,
    'USE_JWT': False,
    'TOKEN_MODEL': None,  # Disable token authentication, use session only
    'USER_DETAILS_SERIALIZER': 'api.serializers.UserSerializer',
    'LOGIN_SERIALIZER': 'api.serializers.LoginSerializer',
}

# Session Security Settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1800  # 30 minutes inactivity timeout
SESSION_SAVE_EVERY_REQUEST = True  # Reset timer on each request (creates inactivity timeout)
SESSION_COOKIE_NAME = 'shinninglight_sessionid'  # Unique name to avoid conflicts with other projects

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False  # JavaScript needs to read this
CSRF_COOKIE_NAME = 'shinninglight_csrftoken'  # Unique name to avoid conflicts with other projects

# Environment-specific cookie settings
if ENV == 'production':
    # Production: HTTPS with cross-subdomain support
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_DOMAIN = '.shininglightschoolsijebuode.com'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_DOMAIN = '.shininglightschoolsijebuode.com'
else:
    # Development: HTTP localhost
    SESSION_COOKIE_SECURE = False  # Allow HTTP
    SESSION_COOKIE_SAMESITE = 'Lax'  # Standard for same-origin
    # No SESSION_COOKIE_DOMAIN for localhost
    CSRF_COOKIE_SECURE = False  # Allow HTTP
    CSRF_COOKIE_SAMESITE = 'Lax'  # Standard for same-origin
    # No CSRF_COOKIE_DOMAIN for localhost

CSRF_TRUSTED_ORIGINS = [
    'https://shininglightschoolsijebuode.com',
    'https://www.shininglightschoolsijebuode.com',
    'https://api.shininglightschoolsijebuode.com',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://localhost:3050',
    'http://127.0.0.1:3050',
    'https://interavailable-lexi-instigative.ngrok-free',
]

# CORS Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'https://shininglightschoolsijebuode.com',
    'https://www.shininglightschoolsijebuode.com',
    'https://api.shininglightschoolsijebuode.com',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://localhost:3050',
    'http://127.0.0.1:3050',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "serverConfig.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'api' / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "serverConfig.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENV == 'production':
    # PostgreSQL configuration for production
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv('DB_NAME', 'shinninglight_db'),
            "USER": os.getenv('DB_USER', 'postgres'),
            "PASSWORD": os.getenv('DB_PASSWORD', ''),
            "HOST": os.getenv('DB_HOST', 'localhost'),
            "PORT": os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # SQLite configuration for development/local
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Cache Configuration
# https://docs.djangoproject.com/en/5.2/topics/cache/

if ENV == 'production':
    # Redis cache for production using django-redis
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'shinninglight',
            'TIMEOUT': 7200,  # 2 hours to match CBT session timeout
        }
    }
else:
    # In-memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 7200,  # 2 hours to match CBT session timeout
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email Configuration
# SMTP backend for both development and production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Email settings
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@shininglightschools.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'admin@shininglightschools.com')

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Backblaze B2 Storage Configuration
# If AWS_ACCESS_KEY_ID is set in env, use B2
if os.getenv('AWS_ACCESS_KEY_ID'):
    INSTALLED_APPS += ['storages']
    
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
    
    # B2/S3 Settings
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'media'
    AWS_DEFAULT_ACL = None # Backblaze B2 buckets are private by default
    
    # Explicitly set Region and Signature Version for B2
    AWS_S3_REGION_NAME = 'us-east-005' 
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # Use B2 for Media, keep local for Static (unless configured otherwise)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # Override MEDIA_URL to point to B2
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/'

# Frontend URL Configuration
if ENV == 'production':
    FRONTEND_URL = 'https://shininglightschoolsijebuode.com'
else:
    FRONTEND_URL = 'http://localhost:3050'

# Contact Email
CONTACT_EMAIL = 'ict@shininglightschoolsijebuode.com'

# External Rendering API (Urlbox, etc)
# External Rendering API (Urlbox, etc)
EXTERNAL_RENDER_API_KEY = os.getenv('EXTERNAL_RENDER_API_KEY')

# Paystack Configuration
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')

# Termii Configuration
TERMII_API_KEY = os.getenv('TERMII_API_KEY')
TERMII_SENDER_ID = os.getenv('TERMII_SENDER_ID', 'ShiningL')
TERMII_BASE_URL = os.getenv('TERMII_BASE_URL', 'https://api.ng.termii.com/api')
